## Base settings ##
# url:  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: å·´å¤å½±éŸ³è¨Šæ¯å½™é›†
description: ğŸ‘½

nav_lists:
  - titles:
      en: About
      zh: å…³äº
      zh-Hans: å…³äº
      zh-Hant: é—œæ–¼
    url: /about.html
  - titles:
      en: Search
      zh: æœç´¢
      zh-Hans: æœç´¢
      zh-Hant: æœå°‹
    url: /search.html

# paths:
#   base: /
#   home: /
#   all:  /all.html
#   rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
# repository:  #e.g. someone/someone.github.io
# repository_tree:  #e.g. master

## Language & timezone ##
lang: zh-Hant
timezone: Asia/Taipei

## Author & social ##
author:
  name: Bashar.Buddha
  # email:  #your Email address e.g. someone@site.com
  # facebook:  #your Facebook username
  # twitter:  #your Twitter username
  # github:  #your GitHub username
  # googleplus:  #your Google+ username
  # weibo:  #your Weibo username
  # douban:  #your Douban username
  # linkedin:  #your Linkedin username

## Comment system (Disqus) ##
disqus:
  shortname: basharbuddha

## Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  # clientID:  #Github Application Client ID
  # clientSecret:  #Github Application Client Secret
  # repository:  #Github repo
  # owner:  #Github repo owner
  # admin: #Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    # - owner

## Google Analytics ##
ga_tracking_id:  UA-112164871-1

## Reading quantity (LeanCloud) ##
leancloud:
  app_id: 3sBjcT3E45n9zVghcgQnc0T5-MdYXbMMI
  app_key: x5Sx0wvrYtDrKupVzvxPbKEE
  app_class: Counter

# mathjax: true

## Paginate ##
paginate: 5
paginate_path: /posts/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: text # text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Algolia ##
algolia:
  application_id: VXNUMUQ10M
  index_name: basharbuddha
  search_only_api_key: 2454842b9872cfac31e11c2427623f10
  nodes_to_index: 'p'

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false
